{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "events-service.fullname" . }}
  labels:
    {{- include "events-service.labels" . | nindent 4 }}
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: >-
      {{ .Release.Namespace }}-{{ include "events-service.fullname" . }}-strip@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "events-service.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}

