apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.secretName }}
  labels:
    {{- include "events-service.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.database.secretKey }}: {{ "postgresql://cms_user:cms_password@events-postgres:5432/events_db" | b64enc | quote }}

